import copy
from datetime import datetime

BUSINESS_TEMPLATES = {
    "manufacturing": {
        "name": "Manufacturing",
        "icon": "🏭",
        "description": "Production, inventory, supply chain, and quality management",
        "departments": [
            {"name": "Executive", "teams": ["Board", "CEO Office"]},
            {"name": "Production", "teams": ["Assembly", "Machining", "Packaging", "Quality Control"]},
            {"name": "Supply Chain", "teams": ["Procurement", "Inventory", "Logistics"]},
            {"name": "Sales & Marketing", "teams": ["Domestic Sales", "Export Sales", "Marketing"]},
            {"name": "Finance", "teams": ["Accounting", "Payroll", "Costing"]},
            {"name": "HR & Admin", "teams": ["Recruitment", "Training", "Administration"]},
            {"name": "Engineering", "teams": ["Product Design", "R&D", "Maintenance"]},
            {"name": "Customer Support", "teams": ["Service Desk", "Field Support"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Executive"},
            {"name": "COO", "level": 2, "department": "Executive"},
            {"name": "Plant Manager", "level": 3, "department": "Production"},
            {"name": "Production Manager", "level": 4, "department": "Production"},
            {"name": "Supply Chain Manager", "level": 4, "department": "Supply Chain"},
            {"name": "Sales Manager", "level": 4, "department": "Sales & Marketing"},
            {"name": "Finance Manager", "level": 4, "department": "Finance"},
            {"name": "HR Manager", "level": 4, "department": "HR & Admin"},
            {"name": "Quality Manager", "level": 4, "department": "Production"},
            {"name": "Engineer", "level": 5, "department": "Engineering"},
            {"name": "Team Lead", "level": 5, "department": "Production"},
            {"name": "Associate", "level": 6, "department": "Production"},
        ],
        "customer_lifecycle": [
            "Lead", "Quote", "Sample Approval", "Order", "Production Planning",
            "Manufacturing", "Quality Check", "Dispatch", "Delivery", "Support"
        ],
        "workflows": ["customer_management", "leave_approval", "purchase_request", "expense_approval",
                      "invoice_approval", "support_ticket", "production_planning", "quality_inspection",
                      "dispatch_approval", "vendor_management", "material_request", "maintenance_request"],
        "dashboards": [
            {"title": "Production Overview", "widgets": ["active_orders", "production_target", "quality_metrics", "machine_status"]},
            {"title": "Inventory Status", "widgets": ["stock_levels", "reorder_alerts", "material_availability"]},
            {"title": "Sales Performance", "widgets": ["pending_quotes", "order_status", "revenue_trends"]},
        ],
        "forms": ["Quotation", "Material Request", "Production Order", "Quality Inspection",
                  "Dispatch Note", "Purchase Order", "Maintenance Request", "Vendor Evaluation"],
        "automations": [
            {"trigger": "quotation_approved", "actions": ["notify_production", "create_production_order", "notify_sales"]},
            {"trigger": "material_request_approved", "actions": ["notify_procurement", "update_inventory", "notify_requestor"]},
            {"trigger": "order_shipped", "actions": ["notify_customer", "update_order_status", "generate_invoice"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Plant Manager": ["production.*", "quality.*", "inventory.read"],
            "Production Manager": ["production.*", "quality.read"],
            "Finance Manager": ["finance.*", "purchase.approve"],
            "Sales Manager": ["sales.*", "customer.*"],
            "Team Lead": ["production.write", "quality.read"],
            "Associate": ["production.read"],
        },
    },
    "construction": {
        "name": "Construction",
        "icon": "🏗️",
        "description": "Project-based construction management with site operations",
        "departments": [
            {"name": "Executive", "teams": ["Board", "MD Office"]},
            {"name": "Projects", "teams": ["Site Execution", "Planning", "Quality Control"]},
            {"name": "Estimation", "teams": ["Quantity Surveying", "Cost Estimation", "Bidding"]},
            {"name": "Procurement", "teams": ["Material Purchase", "Vendor Management", "Equipment Rental"]},
            {"name": "Finance", "teams": ["Accounts", "Budgeting", "Payroll"]},
            {"name": "HR & Admin", "teams": ["Recruitment", "Compliance", "Administration"]},
            {"name": "Sales & Marketing", "teams": ["Business Development", "Marketing", "Customer Relations"]},
            {"name": "Safety & Compliance", "teams": ["Site Safety", "Environmental Compliance"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Executive"},
            {"name": "Project Director", "level": 2, "department": "Projects"},
            {"name": "Project Manager", "level": 3, "department": "Projects"},
            {"name": "Site Engineer", "level": 4, "department": "Projects"},
            {"name": "Quantity Surveyor", "level": 4, "department": "Estimation"},
            {"name": "Procurement Manager", "level": 4, "department": "Procurement"},
            {"name": "Finance Manager", "level": 4, "department": "Finance"},
            {"name": "Safety Officer", "level": 4, "department": "Safety & Compliance"},
            {"name": "Business Development Manager", "level": 4, "department": "Sales & Marketing"},
            {"name": "Supervisor", "level": 5, "department": "Projects"},
            {"name": "Skilled Worker", "level": 6, "department": "Projects"},
        ],
        "customer_lifecycle": [
            "Lead", "Site Visit", "Quotation", "Negotiation", "Approval",
            "Contract", "Execution", "Billing", "Warranty", "Support"
        ],
        "workflows": ["customer_management", "leave_approval", "purchase_request", "expense_approval",
                      "invoice_approval", "support_ticket", "site_inspection", "material_request",
                      "vendor_payment_approval", "project_milestone", "safety_incident", "change_order"],
        "dashboards": [
            {"title": "Project Overview", "widgets": ["active_projects", "pending_quotations", "material_requests", "site_progress"]},
            {"title": "Budget Status", "widgets": ["budget_vs_actual", "cost_overruns", "payment_status"]},
            {"title": "Resource Allocation", "widgets": ["equipment_utilization", "labor_availability", "material_status"]},
        ],
        "forms": ["Quotation", "Site Inspection", "Material Request", "Vendor Request",
                  "Change Order", "Safety Report", "Progress Report", "Payment Application"],
        "automations": [
            {"trigger": "quotation_approved", "actions": ["notify_finance", "generate_purchase_request", "assign_procurement", "notify_manager", "create_project"]},
            {"trigger": "material_delivered", "actions": ["notify_site_engineer", "update_inventory", "notify_procurement"]},
            {"trigger": "project_milestone_reached", "actions": ["notify_client", "generate_invoice", "notify_project_manager"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Project Director": ["projects.*", "estimation.read", "finance.read"],
            "Project Manager": ["projects.*", "estimation.read", "procurement.request"],
            "Site Engineer": ["projects.write", "material.request", "safety.report"],
            "Quantity Surveyor": ["estimation.*", "projects.read"],
            "Finance Manager": ["finance.*", "payment.approve"],
        },
    },
    "healthcare": {
        "name": "Healthcare",
        "icon": "🏥",
        "description": "Patient management, clinical workflows, and compliance",
        "departments": [
            {"name": "Executive", "teams": ["Board", "CEO Office"]},
            {"name": "Medical", "teams": ["Physicians", "Surgeons", "Specialists"]},
            {"name": "Nursing", "teams": ["Ward Nurses", "ICU Nurses", "OPD Nurses"]},
            {"name": "Diagnostics", "teams": ["Lab", "Radiology", "Pharmacy"]},
            {"name": "Administration", "teams": ["Front Desk", "Billing", "Medical Records"]},
            {"name": "Finance", "teams": ["Insurance", "Accounts", "Payroll"]},
            {"name": "HR & Training", "teams": ["Recruitment", "CME", "Compliance"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Executive"},
            {"name": "Medical Director", "level": 2, "department": "Medical"},
            {"name": "Chief Nursing Officer", "level": 3, "department": "Nursing"},
            {"name": "Department Head", "level": 3, "department": "Medical"},
            {"name": "Senior Doctor", "level": 4, "department": "Medical"},
            {"name": "Nurse Manager", "level": 4, "department": "Nursing"},
            {"name": "Lab Manager", "level": 4, "department": "Diagnostics"},
            {"name": "Pharmacist", "level": 4, "department": "Diagnostics"},
            {"name": "Junior Doctor", "level": 5, "department": "Medical"},
            {"name": "Staff Nurse", "level": 5, "department": "Nursing"},
            {"name": "Lab Technician", "level": 5, "department": "Diagnostics"},
            {"name": "Front Desk Officer", "level": 5, "department": "Administration"},
        ],
        "customer_lifecycle": [
            "Inquiry", "Appointment Scheduled", "Registration", "Consultation",
            "Diagnosis", "Treatment", "Follow-up", "Recovery", "Discharge", "Wellness"
        ],
        "workflows": ["patient_registration", "appointment_booking", "lab_test_request", "prescription_approval",
                      "discharge_process", "insurance_claim", "leave_approval", "expense_approval",
                      "support_ticket", "pharmacy_dispense", "medical_record_request"],
        "dashboards": [
            {"title": "Clinical Overview", "widgets": ["patient_count", "doctors_available", "lab_reports", "pharmacy_status"]},
            {"title": "Appointments", "widgets": ["today_appointments", "waiting_patients", "cancellations"]},
            {"title": "Revenue", "widgets": ["billing_summary", "insurance_claims", "collection_status"]},
        ],
        "forms": ["Patient Registration", "Lab Test Request", "Prescription", "Discharge Summary",
                  "Insurance Claim", "Medical Certificate", "Referral Form", "Consent Form"],
        "automations": [
            {"trigger": "appointment_booked", "actions": ["notify_patient", "assign_doctor", "send_reminder"]},
            {"trigger": "lab_report_ready", "actions": ["notify_doctor", "update_patient_record", "notify_patient"]},
            {"trigger": "discharge_summary_signed", "actions": ["notify_family", "generate_bill", "update_bed_availability", "schedule_followup"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Medical Director": ["medical.*", "diagnostics.read", "administration.read"],
            "Department Head": ["medical.*", "nursing.read", "diagnostics.request"],
            "Senior Doctor": ["medical.write", "prescription.write", "diagnostics.request"],
            "Junior Doctor": ["medical.read", "prescription.read", "diagnostics.request"],
            "Staff Nurse": ["nursing.*", "patient.read", "administration.read"],
            "Lab Technician": ["diagnostics.lab.*", "patient.read"],
        },
    },
    "hospital": {
        "name": "Hospital",
        "icon": "🏨",
        "description": "Multi-specialty hospital with full inpatient and outpatient management",
        "extends": "healthcare",
        "departments": [
            {"name": "Executive", "teams": ["Board", "CEO Office", "Quality"]},
            {"name": "Medical", "teams": ["Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Gynecology", "Oncology", "Emergency"]},
            {"name": "Surgical", "teams": ["OT Management", "Anesthesiology", "Sterilization"]},
            {"name": "Nursing", "teams": ["ICU", "General Wards", "OPD", "Emergency"]},
            {"name": "Diagnostics", "teams": ["Lab", "Radiology", "Pathology", "Pharmacy"]},
            {"name": "Administration", "teams": ["Front Desk", "IP Billing", "OP Billing", "Medical Records", "Insurance"]},
            {"name": "Finance", "teams": ["Accounts", "Payroll", "TPA"]},
            {"name": "HR & Training", "teams": ["Recruitment", "CME", "Compliance"]},
            {"name": "Facilities", "teams": ["Housekeeping", "Security", "Cafeteria", "Ambulance"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Executive"},
            {"name": "Medical Superintendent", "level": 2, "department": "Medical"},
            {"name": "Chief of Nursing", "level": 3, "department": "Nursing"},
            {"name": "HOD", "level": 3, "department": "Medical"},
            {"name": "Consultant", "level": 4, "department": "Medical"},
            {"name": "Senior Resident", "level": 5, "department": "Medical"},
            {"name": "Junior Resident", "level": 6, "department": "Medical"},
            {"name": "Nurse Manager", "level": 4, "department": "Nursing"},
            {"name": "Staff Nurse", "level": 5, "department": "Nursing"},
            {"name": "Lab Manager", "level": 4, "department": "Diagnostics"},
            {"name": "Pharmacist", "level": 5, "department": "Diagnostics"},
            {"name": "Billing Officer", "level": 5, "department": "Administration"},
        ],
        "customer_lifecycle": [
            "Inquiry", "Appointment", "Registration", "Consultation", "Diagnosis",
            "Admission", "Treatment", "Surgery", "Discharge", "Follow-up"
        ],
        "workflows": ["patient_registration", "appointment_booking", "ip_admission", "ot_scheduling",
                      "lab_test_request", "prescription_approval", "discharge_process", "insurance_claim",
                      "leave_approval", "expense_approval", "blood_bank_request", "ambulance_request",
                      "pharmacy_dispense", "medical_record_request", "complaint_registration"],
        "dashboards": [
            {"title": "Hospital Overview", "widgets": ["bed_occupancy", "patient_count", "ot_schedule", "emergency_cases"]},
            {"title": "OPD Status", "widgets": ["today_appointments", "waiting_time", "department_load"]},
            {"title": "Revenue & Billing", "widgets": ["daily_collection", "insurance_pending", "pharmacy_sales"]},
        ],
        "forms": ["Patient Registration", "IP Admission", "OT Schedule", "Lab Test", "Prescription",
                  "Discharge Summary", "Insurance Claim", "Nursing Notes", "Medical Certificate"],
        "automations": [
            {"trigger": "patient_admitted", "actions": ["assign_bed", "notify_nursing_station", "assign_consultant", "create_medical_record"]},
            {"trigger": "lab_report_ready", "actions": ["notify_doctor", "update_emr", "notify_patient_portal"]},
            {"trigger": "discharge_initiated", "actions": ["generate_bill", "notify_pharmacy", "schedule_followup", "release_bed"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Medical Superintendent": ["medical.*", "nursing.*", "administration.read", "diagnostics.read"],
            "HOD": ["medical.*", "nursing.read", "diagnostics.request"],
            "Consultant": ["medical.write", "prescription.write", "diagnostics.request"],
            "Senior Resident": ["medical.write", "prescription.read"],
            "Staff Nurse": ["nursing.*", "patient.read", "administration.read"],
            "Billing Officer": ["administration.billing.*", "finance.read"],
        },
    },
    "clinic": {
        "name": "Clinic",
        "icon": "🩺",
        "description": "Small clinic with outpatient consultation and pharmacy",
        "departments": [
            {"name": "Management", "teams": ["Owner", "Administration"]},
            {"name": "Medical", "teams": ["Doctors", "Nurses"]},
            {"name": "Pharmacy", "teams": ["Dispensing", "Inventory"]},
            {"name": "Lab", "teams": ["Testing", "Reports"]},
            {"name": "Front Desk", "teams": ["Reception", "Billing", "Appointments"]},
        ],
        "roles": [
            {"name": "Owner/Director", "level": 1, "department": "Management"},
            {"name": "Chief Doctor", "level": 2, "department": "Medical"},
            {"name": "General Practitioner", "level": 3, "department": "Medical"},
            {"name": "Staff Nurse", "level": 4, "department": "Medical"},
            {"name": "Pharmacist", "level": 3, "department": "Pharmacy"},
            {"name": "Lab Technician", "level": 4, "department": "Lab"},
            {"name": "Receptionist", "level": 4, "department": "Front Desk"},
            {"name": "Billing Clerk", "level": 5, "department": "Front Desk"},
        ],
        "customer_lifecycle": ["Inquiry", "Appointment", "Consultation", "Diagnosis", "Treatment", "Follow-up"],
        "workflows": ["patient_registration", "appointment_booking", "lab_test_request", "prescription",
                      "leave_approval", "pharmacy_dispense"],
        "dashboards": [
            {"title": "Clinic Overview", "widgets": ["today_appointments", "patient_count", "pharmacy_dispensed", "lab_pending"]},
            {"title": "Revenue", "widgets": ["daily_collection", "monthly_revenue", "pending_payments"]},
        ],
        "forms": ["Patient Registration", "Prescription", "Lab Test", "Pharmacy Dispense", "Referral"],
        "automations": [
            {"trigger": "appointment_booked", "actions": ["send_confirmation", "assign_doctor"]},
            {"trigger": "lab_test_ordered", "actions": ["notify_lab", "update_patient_record"]},
        ],
        "permissions": {
            "Owner/Director": ["all"],
            "Chief Doctor": ["medical.*", "patient.read", "pharmacy.read"],
            "General Practitioner": ["medical.write", "prescription.write"],
            "Pharmacist": ["pharmacy.*", "patient.read"],
        },
    },
    "pharmacy": {
        "name": "Pharmacy",
        "icon": "💊",
        "description": "Retail and wholesale pharmacy with inventory management",
        "departments": [
            {"name": "Management", "teams": ["Owner", "Operations"]},
            {"name": "Dispensing", "teams": ["Prescription Counter", "OTC Sales"]},
            {"name": "Inventory", "teams": ["Stock Management", "Expiry Tracking"]},
            {"name": "Procurement", "teams": ["Vendor Management", "Purchase"]},
            {"name": "Finance", "teams": ["Billing", "Accounts"]},
        ],
        "roles": [
            {"name": "Owner/Manager", "level": 1, "department": "Management"},
            {"name": "Chief Pharmacist", "level": 2, "department": "Dispensing"},
            {"name": "Pharmacist", "level": 3, "department": "Dispensing"},
            {"name": "Pharmacy Technician", "level": 4, "department": "Dispensing"},
            {"name": "Inventory Manager", "level": 3, "department": "Inventory"},
            {"name": "Procurement Officer", "level": 4, "department": "Procurement"},
            {"name": "Billing Clerk", "level": 5, "department": "Finance"},
        ],
        "customer_lifecycle": ["Walk-in", "Prescription", "Order", "Dispensed", "Follow-up", "Refill"],
        "workflows": ["prescription_dispense", "purchase_request", "expense_approval",
                      "supplier_order", "stock_transfer", "expiry_disposal", "leave_approval"],
        "dashboards": [
            {"title": "Pharmacy Overview", "widgets": ["prescriptions_today", "stock_alerts", "expiry_alerts", "sales_today"]},
            {"title": "Inventory", "widgets": ["low_stock_items", "expiring_items", "top_selling"]},
        ],
        "forms": ["Prescription Order", "Purchase Order", "Stock Transfer", "Expiry Disposal", "Supplier Order"],
        "automations": [
            {"trigger": "prescription_dispensed", "actions": ["update_inventory", "generate_label", "notify_customer"]},
            {"trigger": "stock_below_threshold", "actions": ["notify_procurement", "create_purchase_order"]},
        ],
        "permissions": {
            "Owner/Manager": ["all"],
            "Chief Pharmacist": ["dispensing.*", "inventory.*", "procurement.request"],
            "Pharmacist": ["dispensing.*", "inventory.read"],
        },
    },
    "school": {
        "name": "School",
        "icon": "🏫",
        "description": "K-12 school management with academics and administration",
        "departments": [
            {"name": "Management", "teams": ["Board", "Principal Office"]},
            {"name": "Academic", "teams": ["Primary", "Middle", "High School"]},
            {"name": "Administration", "teams": ["Admissions", "Examinations", "Transport"]},
            {"name": "Finance", "teams": ["Fees", "Accounts", "Payroll"]},
            {"name": "HR", "teams": ["Teacher Recruitment", "Staff Management"]},
            {"name": "Extracurricular", "teams": ["Sports", "Arts", "Clubs"]},
        ],
        "roles": [
            {"name": "Principal", "level": 1, "department": "Management"},
            {"name": "Vice Principal", "level": 2, "department": "Academic"},
            {"name": "Academic Coordinator", "level": 3, "department": "Academic"},
            {"name": "Head Teacher", "level": 4, "department": "Academic"},
            {"name": "Teacher", "level": 5, "department": "Academic"},
            {"name": "Administration Officer", "level": 4, "department": "Administration"},
            {"name": "Accountant", "level": 4, "department": "Finance"},
            {"name": "Librarian", "level": 5, "department": "Academic"},
        ],
        "customer_lifecycle": ["Inquiry", "Application", "Entrance Test", "Interview", "Admission", "Enrolled", "Graduated"],
        "workflows": ["student_admission", "fee_collection", "leave_approval", "exam_planning",
                      "transport_management", "event_management", "complaint_registration"],
        "dashboards": [
            {"title": "School Overview", "widgets": ["student_count", "teacher_count", "attendance_today", "fee_collection"]},
            {"title": "Academic", "widgets": ["class_performance", "exam_schedule", "homework_status"]},
        ],
        "forms": ["Admission Application", "Fee Receipt", "Transfer Certificate", "Exam Registration", "Leave Application"],
        "automations": [
            {"trigger": "admission_confirmed", "actions": ["generate_student_id", "assign_class", "notify_parents", "create_profile"]},
            {"trigger": "fee_paid", "actions": ["generate_receipt", "update_fee_record", "notify_parents"]},
        ],
        "permissions": {
            "Principal": ["all"],
            "Academic Coordinator": ["academic.*", "teacher.read", "student.read"],
            "Teacher": ["academic.write", "student.read", "attendance.write"],
            "Accountant": ["finance.*", "student.read"],
        },
    },
    "college": {
        "name": "College",
        "icon": "🎓",
        "description": "Undergraduate and graduate college management",
        "departments": [
            {"name": "Management", "teams": ["Governing Body", "Principal Office"]},
            {"name": "Academic", "teams": ["Science", "Arts", "Commerce", "Engineering"]},
            {"name": "Administration", "teams": ["Admissions", "Examinations", "Student Affairs"]},
            {"name": "Finance", "teams": ["Fees", "Accounts", "Grants"]},
            {"name": "HR", "teams": ["Faculty Recruitment", "Staff Management"]},
            {"name": "Library", "teams": ["Digital Library", "Reference Section"]},
            {"name": "Student Services", "teams": ["Placement", "Counseling", "Hostel"]},
        ],
        "roles": [
            {"name": "Principal", "level": 1, "department": "Management"},
            {"name": "Vice Principal", "level": 2, "department": "Academic"},
            {"name": "HOD", "level": 3, "department": "Academic"},
            {"name": "Professor", "level": 4, "department": "Academic"},
            {"name": "Assistant Professor", "level": 5, "department": "Academic"},
            {"name": "Administration Officer", "level": 4, "department": "Administration"},
            {"name": "Placement Officer", "level": 4, "department": "Student Services"},
            {"name": "Librarian", "level": 4, "department": "Library"},
            {"name": "Accountant", "level": 5, "department": "Finance"},
        ],
        "customer_lifecycle": ["Inquiry", "Application", "Entrance Exam", "Interview", "Admission", "Enrolled", "Graduated", "Alumni"],
        "workflows": ["student_admission", "fee_collection", "leave_approval", "exam_planning",
                      "placement_drive", "library_management", "event_management", "hostel_allocation"],
        "dashboards": [
            {"title": "College Overview", "widgets": ["student_count", "faculty_count", "attendance", "placement_status"]},
            {"title": "Examinations", "widgets": ["exam_schedule", "result_pending", "grade_distribution"]},
        ],
        "forms": ["Admission Application", "Exam Registration", "Fee Payment", "Leave Application", "Hostel Application"],
        "automations": [
            {"trigger": "admission_confirmed", "actions": ["generate_student_id", "assign_department", "notify_student", "create_email"]},
            {"trigger": "exam_result_published", "actions": ["notify_students", "update_records", "generate_grade_card"]},
        ],
        "permissions": {
            "Principal": ["all"],
            "HOD": ["academic.*", "faculty.read", "student.read"],
            "Professor": ["academic.write", "student.read", "exam.write"],
            "Placement Officer": ["placement.*", "student.read"],
        },
    },
    "university": {
        "name": "University",
        "icon": "🏛️",
        "description": "Multi-department university with research and governance",
        "departments": [
            {"name": "Chancellor Office", "teams": ["Governing Council", "Vice Chancellor Office"]},
            {"name": "Academic Affairs", "teams": ["Schools", "Departments", "Research"]},
            {"name": "Administration", "teams": ["Admissions", "Examinations", "Student Affairs", "International Relations"]},
            {"name": "Finance", "teams": ["Accounts", "Grants", "Research Funding"]},
            {"name": "HR", "teams": ["Faculty Affairs", "Staff Recruitment", "Development"]},
            {"name": "Research", "teams": ["PhD Programs", "Publications", "Innovation Lab"]},
            {"name": "Library", "teams": ["Digital Resources", "Archives"]},
            {"name": "Student Services", "teams": ["Placement", "Counseling", "Hostels", "Sports"]},
        ],
        "roles": [
            {"name": "Vice Chancellor", "level": 1, "department": "Chancellor Office"},
            {"name": "Registrar", "level": 2, "department": "Administration"},
            {"name": "Dean", "level": 3, "department": "Academic Affairs"},
            {"name": "HOD", "level": 4, "department": "Academic Affairs"},
            {"name": "Professor", "level": 4, "department": "Academic Affairs"},
            {"name": "Associate Professor", "level": 5, "department": "Academic Affairs"},
            {"name": "Assistant Professor", "level": 6, "department": "Academic Affairs"},
            {"name": "Research Fellow", "level": 5, "department": "Research"},
            {"name": "Placement Director", "level": 4, "department": "Student Services"},
            {"name": "Finance Officer", "level": 4, "department": "Finance"},
        ],
        "customer_lifecycle": ["Inquiry", "Application", "Entrance Exam", "Counselling", "Admission", "Enrolled", "Graduated", "Alumni"],
        "workflows": ["student_admission", "fee_collection", "leave_approval", "exam_planning",
                      "research_grant", "publication_approval", "placement_drive", "event_management",
                      "hostel_allocation", "scholarship_approval", "faculty_recruitment"],
        "dashboards": [
            {"title": "University Overview", "widgets": ["student_population", "faculty_count", "research_publications", "accreditation_status"]},
            {"title": "Research", "widgets": ["active_grants", "publications", "phd_students", "collaborations"]},
            {"title": "Placements", "widgets": ["placed_students", "companies_visited", "average_package"]},
        ],
        "forms": ["Admission Application", "Research Grant Proposal", "Publication Approval", "Fee Payment", "Scholarship Application"],
        "automations": [
            {"trigger": "admission_confirmed", "actions": ["generate_enrollment_id", "assign_faculty_advisor", "create_portal_access", "notify_student"]},
            {"trigger": "research_grant_approved", "actions": ["allocate_funds", "notify_researcher", "create_project", "schedule_review"]},
        ],
        "permissions": {
            "Vice Chancellor": ["all"],
            "Registrar": ["administration.*", "academic.read", "finance.read"],
            "Dean": ["academic.*", "faculty.*", "research.read"],
            "HOD": ["academic.*", "faculty.read", "student.read"],
            "Professor": ["academic.write", "research.write", "student.read"],
        },
    },
    "retail_store": {
        "name": "Retail Store",
        "icon": "🏪",
        "description": "Single and multi-store retail with inventory and POS",
        "departments": [
            {"name": "Management", "teams": ["Store Manager", "Area Managers"]},
            {"name": "Sales Floor", "teams": ["Customer Service", "Cashiers", "Sales Associates"]},
            {"name": "Inventory", "teams": ["Stock Management", "Receiving", "Visual Merchandising"]},
            {"name": "Marketing", "teams": ["Promotions", "Loyalty", "Social Media"]},
            {"name": "Finance", "teams": ["Accounts", "Payroll"]},
            {"name": "E-commerce", "teams": ["Online Orders", "Digital Marketing"]},
        ],
        "roles": [
            {"name": "Store Manager", "level": 1, "department": "Management"},
            {"name": "Assistant Manager", "level": 2, "department": "Management"},
            {"name": "Department Manager", "level": 3, "department": "Sales Floor"},
            {"name": "Sales Associate", "level": 4, "department": "Sales Floor"},
            {"name": "Cashier", "level": 5, "department": "Sales Floor"},
            {"name": "Inventory Clerk", "level": 4, "department": "Inventory"},
            {"name": "Marketing Coordinator", "level": 4, "department": "Marketing"},
            {"name": "Accountant", "level": 4, "department": "Finance"},
        ],
        "customer_lifecycle": ["Awareness", "Visit", "Browse", "Purchase", "Post-Purchase", "Loyalty", "Advocacy"],
        "workflows": ["customer_management", "leave_approval", "purchase_request", "expense_approval",
                      "invoice_approval", "support_ticket", "stock_transfer", "price_change",
                      "promotion_approval", "supplier_order", "return_refund"],
        "dashboards": [
            {"title": "Sales Overview", "widgets": ["daily_sales", "foot_traffic", "conversion_rate", "average_transaction"]},
            {"title": "Inventory", "widgets": ["stock_levels", "best_sellers", "low_stock_alerts", "inventory_turnover"]},
            {"title": "Customer Insights", "widgets": ["loyalty_members", "customer_satisfaction", "repeat_rate"]},
        ],
        "forms": ["Purchase Order", "Stock Transfer", "Price Change Request", "Promotion Approval", "Return/Refund"],
        "automations": [
            {"trigger": "sale_completed", "actions": ["update_inventory", "update_loyalty_points", "send_receipt", "update_dashboard"]},
            {"trigger": "stock_below_reorder", "actions": ["notify_inventory_manager", "create_purchase_order", "notify_supplier"]},
            {"trigger": "return_initiated", "actions": ["approve_return", "update_inventory", "process_refund", "notify_customer"]},
        ],
        "permissions": {
            "Store Manager": ["all"],
            "Assistant Manager": ["sales.*", "inventory.*", "staff.read"],
            "Department Manager": ["sales.write", "inventory.read", "customer.read"],
            "Sales Associate": ["sales.write", "customer.read"],
            "Cashier": ["sales.cashier", "customer.read"],
        },
    },
    "wholesale": {
        "name": "Wholesale",
        "icon": "📦",
        "description": "B2B wholesale with bulk orders and distributor management",
        "departments": [
            {"name": "Management", "teams": ["Director", "Operations"]},
            {"name": "Sales", "teams": ["Key Accounts", "Field Sales", "Tele Sales"]},
            {"name": "Procurement", "teams": ["Sourcing", "Vendor Management"]},
            {"name": "Warehouse", "teams": ["Receiving", "Picking", "Shipping"]},
            {"name": "Finance", "teams": ["Accounts", "Credit Control", "Payroll"]},
            {"name": "Logistics", "teams": ["Dispatch", "Fleet Management", "Route Planning"]},
        ],
        "roles": [
            {"name": "Director", "level": 1, "department": "Management"},
            {"name": "Operations Manager", "level": 2, "department": "Management"},
            {"name": "Sales Manager", "level": 3, "department": "Sales"},
            {"name": "Key Account Manager", "level": 4, "department": "Sales"},
            {"name": "Procurement Officer", "level": 4, "department": "Procurement"},
            {"name": "Warehouse Supervisor", "level": 4, "department": "Warehouse"},
            {"name": "Logistics Coordinator", "level": 4, "department": "Logistics"},
            {"name": "Credit Controller", "level": 4, "department": "Finance"},
            {"name": "Sales Representative", "level": 5, "department": "Sales"},
        ],
        "customer_lifecycle": ["Lead", "Quote", "Sample Request", "Bulk Order", "Credit Check", "Dispatch", "Delivery", "Payment", "Repeat Order"],
        "workflows": ["customer_management", "leave_approval", "purchase_request", "expense_approval",
                      "invoice_approval", "support_ticket", "credit_limit_approval", "bulk_order",
                      "dispatch_approval", "supplier_payment", "stock_transfer"],
        "dashboards": [
            {"title": "Sales Overview", "widgets": ["bulk_orders", "pending_quotes", "credit_approvals", "revenue"]},
            {"title": "Warehouse", "widgets": ["stock_levels", "picking_status", "dispatch_queue", "inventory_value"]},
            {"title": "Accounts", "widgets": ["receivables", "payables", "credit_utilization"]},
        ],
        "forms": ["Bulk Order", "Credit Application", "Purchase Order", "Dispatch Note", "Supplier Payment"],
        "automations": [
            {"trigger": "bulk_order_confirmed", "actions": ["check_credit", "allocate_inventory", "notify_warehouse", "create_invoice"]},
            {"trigger": "payment_received", "actions": ["update_receivables", "send_receipt", "update_credit_limit", "notify_sales"]},
        ],
        "permissions": {
            "Director": ["all"],
            "Operations Manager": ["operations.*", "sales.read", "finance.read"],
            "Sales Manager": ["sales.*", "customer.*", "credit.read"],
            "Warehouse Supervisor": ["warehouse.*", "inventory.*"],
            "Credit Controller": ["finance.credit.*", "customer.read"],
        },
    },
    "logistics": {
        "name": "Logistics",
        "icon": "🚚",
        "description": "Transport, fleet, and supply chain logistics management",
        "departments": [
            {"name": "Management", "teams": ["CEO", "Operations"]},
            {"name": "Fleet Operations", "teams": ["Dispatch", "Tracking", "Driver Management"]},
            {"name": "Warehousing", "teams": ["Receiving", "Storage", "Packing"]},
            {"name": "Customer Service", "teams": ["Booking", "Tracking Support", "Complaints"]},
            {"name": "Finance", "teams": ["Billing", "Payroll", "Fuel Management"]},
            {"name": "Maintenance", "teams": ["Workshop", "Tyre Management", "Breakdown"]},
            {"name": "Sales", "teams": ["Business Development", "Key Accounts"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Management"},
            {"name": "Operations Manager", "level": 2, "department": "Fleet Operations"},
            {"name": "Fleet Manager", "level": 3, "department": "Fleet Operations"},
            {"name": "Dispatch Coordinator", "level": 4, "department": "Fleet Operations"},
            {"name": "Warehouse Manager", "level": 3, "department": "Warehousing"},
            {"name": "Customer Service Manager", "level": 3, "department": "Customer Service"},
            {"name": "Billing Officer", "level": 5, "department": "Finance"},
            {"name": "Maintenance Manager", "level": 4, "department": "Maintenance"},
            {"name": "Driver", "level": 6, "department": "Fleet Operations"},
        ],
        "customer_lifecycle": ["Inquiry", "Quote", "Booking", "Pickup", "In Transit", "Delivered", "Feedback"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "support_ticket",
                      "booking_confirmation", "dispatch_planning", "driver_assignment", "breakdown_report",
                      "fuel_expense", "invoice_approval", "damage_report"],
        "dashboards": [
            {"title": "Operations", "widgets": ["active_shipments", "fleet_utilization", "on_time_delivery", "pending_pickups"]},
            {"title": "Fleet Status", "widgets": ["vehicle_status", "drivers_available", "maintenance_due", "fuel_efficiency"]},
            {"title": "Finance", "widgets": ["revenue", "outstanding_payments", "fuel_costs", "profit_per_route"]},
        ],
        "forms": ["Booking Order", "Dispatch Note", "Driver Assignment", "Fuel Expense", "Breakdown Report", "Damage Report"],
        "automations": [
            {"trigger": "booking_confirmed", "actions": ["assign_vehicle", "assign_driver", "notify_customer", "update_schedule"]},
            {"trigger": "delivery_confirmed", "actions": ["generate_invoice", "notify_customer", "release_vehicle", "update_status"]},
            {"trigger": "vehicle_due_maintenance", "actions": ["notify_maintenance", "schedule_service", "assign_replacement"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Operations Manager": ["operations.*", "fleet.*", "customer.read"],
            "Fleet Manager": ["fleet.*", "driver.*", "maintenance.read"],
            "Warehouse Manager": ["warehouse.*", "inventory.*"],
            "Customer Service Manager": ["customer_service.*", "booking.*", "tracking.read"],
        },
    },
    "transportation": {
        "name": "Transportation",
        "icon": "🚌",
        "description": "Passenger transport, fleet management, and routing",
        "extends": "logistics",
        "departments": [
            {"name": "Management", "teams": ["Director", "Operations"]},
            {"name": "Fleet", "teams": ["Dispatch", "Drivers", "Scheduling"]},
            {"name": "Routes", "teams": ["Route Planning", "Ticketing"]},
            {"name": "Customer Service", "teams": ["Booking", "Support", "Lost & Found"]},
            {"name": "Finance", "teams": ["Billing", "Fuel", "Toll Management"]},
            {"name": "Maintenance", "teams": ["Workshop", "Breakdown"]},
        ],
        "roles": [
            {"name": "Director", "level": 1, "department": "Management"},
            {"name": "Operations Manager", "level": 2, "department": "Fleet"},
            {"name": "Route Manager", "level": 3, "department": "Routes"},
            {"name": "Scheduler", "level": 4, "department": "Fleet"},
            {"name": "Driver", "level": 5, "department": "Fleet"},
            {"name": "Ticketing Officer", "level": 5, "department": "Routes"},
            {"name": "Customer Service Rep", "level": 5, "department": "Customer Service"},
        ],
        "customer_lifecycle": ["Inquiry", "Booking", "Ticketing", "Boarding", "Journey", "Disembark", "Feedback"],
        "workflows": ["booking_confirmation", "leave_approval", "expense_approval", "support_ticket",
                      "route_change_approval", "incident_report", "fuel_expense", "driver_assignment"],
        "dashboards": [
            {"title": "Fleet Overview", "widgets": ["active_vehicles", "routes_active", "passenger_count", "on_time_rate"]},
            {"title": "Revenue", "widgets": ["ticket_sales", "occupancy_rate", "route_profitability"]},
        ],
        "forms": ["Booking", "Incident Report", "Fuel Expense", "Route Change Request", "Maintenance Request"],
        "automations": [
            {"trigger": "booking_made", "actions": ["assign_vehicle", "issue_ticket", "notify_driver", "update_manifest"]},
            {"trigger": "incident_reported", "actions": ["notify_manager", "log_incident", "notify_safety_team"]},
        ],
        "permissions": {
            "Director": ["all"],
            "Operations Manager": ["fleet.*", "routes.*", "customer_service.read"],
            "Route Manager": ["routes.*", "scheduling.*"],
        },
    },
    "real_estate": {
        "name": "Real Estate",
        "icon": "🏠",
        "description": "Property sales, rentals, and brokerage management",
        "departments": [
            {"name": "Management", "teams": ["Director", "Operations"]},
            {"name": "Sales", "teams": ["Residential", "Commercial", "Luxury"]},
            {"name": "Rentals", "teams": ["Leasing", "Tenant Management"]},
            {"name": "Marketing", "teams": ["Digital", "Print", "Open Houses"]},
            {"name": "Legal", "teams": ["Documentation", "Compliance"]},
            {"name": "Finance", "teams": ["Accounts", "Commissions"]},
            {"name": "Property Management", "teams": ["Maintenance", "Inspections"]},
        ],
        "roles": [
            {"name": "Director", "level": 1, "department": "Management"},
            {"name": "Branch Manager", "level": 2, "department": "Management"},
            {"name": "Sales Manager", "level": 3, "department": "Sales"},
            {"name": "Real Estate Agent", "level": 4, "department": "Sales"},
            {"name": "Leasing Agent", "level": 4, "department": "Rentals"},
            {"name": "Marketing Coordinator", "level": 4, "department": "Marketing"},
            {"name": "Legal Officer", "level": 4, "department": "Legal"},
            {"name": "Property Manager", "level": 4, "department": "Property Management"},
            {"name": "Accountant", "level": 5, "department": "Finance"},
        ],
        "customer_lifecycle": ["Lead", "Property Viewing", "Offer", "Negotiation", "Agreement", "Closing", "Post-Sale", "Referral"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "support_ticket",
                      "property_listing_approval", "offer_management", "commission_approval",
                      "agreement_generation", "inspection_scheduling", "maintenance_request"],
        "dashboards": [
            {"title": "Sales Pipeline", "widgets": ["active_listings", "pending_offers", "closing_soon", "commission_forecast"]},
            {"title": "Property Status", "widgets": ["available_properties", "under_contract", "sold_this_month", "price_trends"]},
            {"title": "Agent Performance", "widgets": ["top_agents", "conversion_rate", "showings_scheduled"]},
        ],
        "forms": ["Property Listing", "Offer Sheet", "Agreement Draft", "Inspection Request", "Maintenance Request", "Commission Sheet"],
        "automations": [
            {"trigger": "offer_accepted", "actions": ["notify_legal", "generate_agreement", "update_property_status", "notify_buyer", "notify_seller"]},
            {"trigger": "property_listed", "actions": ["notify_agents", "post_to_portals", "create_marketing_campaign", "notify_potential_buyers"]},
        ],
        "permissions": {
            "Director": ["all"],
            "Branch Manager": ["sales.*", "rentals.*", "finance.read", "marketing.*"],
            "Sales Manager": ["sales.*", "property.*", "commission.read"],
            "Real Estate Agent": ["sales.write", "property.read", "customer.read"],
            "Legal Officer": ["legal.*", "property.read", "customer.read"],
        },
    },
    "software_company": {
        "name": "Software Company",
        "icon": "💻",
        "description": "Product development, SaaS, and engineering management",
        "departments": [
            {"name": "Executive", "teams": ["CEO", "CTO", "CPO"]},
            {"name": "Engineering", "teams": ["Frontend", "Backend", "DevOps", "QA", "Mobile"]},
            {"name": "Product", "teams": ["Product Management", "UI/UX", "Research"]},
            {"name": "Sales", "teams": ["Enterprise Sales", "SMB Sales", "Sales Development"]},
            {"name": "Marketing", "teams": ["Digital Marketing", "Content", "Events"]},
            {"name": "Customer Success", "teams": ["Onboarding", "Support", "Account Management"]},
            {"name": "Finance", "teams": ["Accounts", "Payroll"]},
            {"name": "HR", "teams": ["Talent Acquisition", "Culture", "L&D"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Executive"},
            {"name": "CTO", "level": 2, "department": "Executive"},
            {"name": "Engineering Manager", "level": 3, "department": "Engineering"},
            {"name": "Product Manager", "level": 3, "department": "Product"},
            {"name": "Senior Developer", "level": 4, "department": "Engineering"},
            {"name": "Developer", "level": 5, "department": "Engineering"},
            {"name": "QA Engineer", "level": 5, "department": "Engineering"},
            {"name": "UI/UX Designer", "level": 4, "department": "Product"},
            {"name": "Sales Manager", "level": 3, "department": "Sales"},
            {"name": "Customer Success Manager", "level": 4, "department": "Customer Success"},
            {"name": "Marketing Manager", "level": 4, "department": "Marketing"},
            {"name": "DevOps Engineer", "level": 4, "department": "Engineering"},
        ],
        "customer_lifecycle": [
            "Lead", "Demo", "Proposal", "Contract", "Development",
            "Testing", "Deployment", "Support", "Renewal"
        ],
        "workflows": ["customer_management", "leave_approval", "purchase_request", "expense_approval",
                      "invoice_approval", "support_ticket", "bug_reporting", "feature_request",
                      "code_review", "deployment_approval", "sprint_planning", "release_management"],
        "dashboards": [
            {"title": "Engineering", "widgets": ["active_projects", "sprint_progress", "bugs", "releases", "customer_tickets"]},
            {"title": "Sales Pipeline", "widgets": ["deals_stage", "demo_conversion", "arr_forecast", "churn_rate"]},
            {"title": "Product Analytics", "widgets": ["feature_adoption", "user_engagement", "performance_metrics"]},
        ],
        "forms": ["Bug Report", "Feature Request", "Release Note", "Sprint Plan", "Deployment Request", "Incident Report"],
        "automations": [
            {"trigger": "bug_reported", "actions": ["assign_developer", "notify_qa", "create_task", "update_backlog"]},
            {"trigger": "deployment_approved", "actions": ["trigger_deployment_pipeline", "notify_team", "update_changelog", "notify_stakeholders"]},
            {"trigger": "support_ticket_escalated", "actions": ["notify_customer_success", "assign_senior_dev", "update_priority"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "CTO": ["engineering.*", "product.read", "devops.*"],
            "Engineering Manager": ["engineering.*", "qa.*", "deployment.approve"],
            "Product Manager": ["product.*", "engineering.read", "customer.read"],
            "Senior Developer": ["engineering.write", "code_review", "deployment.request"],
            "Developer": ["engineering.write", "code.write"],
            "QA Engineer": ["qa.*", "engineering.read"],
            "Customer Success Manager": ["customer_success.*", "support.*", "customer.read"],
        },
    },
    "it_services": {
        "name": "IT Services",
        "icon": "🖥️",
        "description": "IT consulting, managed services, and outsourcing",
        "departments": [
            {"name": "Management", "teams": ["CEO", "Delivery"]},
            {"name": "Delivery", "teams": ["Project Management", "Development", "QA"]},
            {"name": "Infrastructure", "teams": ["Network", "Cloud", "Security"]},
            {"name": "Managed Services", "teams": ["Support Desk", "Remote Monitoring", "SLA Management"]},
            {"name": "Sales", "teams": ["Account Management", "Business Development"]},
            {"name": "Finance", "teams": ["Accounts", "Billing"]},
            {"name": "HR", "teams": ["Recruitment", "Training"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Management"},
            {"name": "Delivery Head", "level": 2, "department": "Delivery"},
            {"name": "Project Manager", "level": 3, "department": "Delivery"},
            {"name": "Technical Lead", "level": 4, "department": "Delivery"},
            {"name": "Software Engineer", "level": 5, "department": "Delivery"},
            {"name": "Network Engineer", "level": 4, "department": "Infrastructure"},
            {"name": "Service Desk Lead", "level": 4, "department": "Managed Services"},
            {"name": "Support Engineer", "level": 5, "department": "Managed Services"},
            {"name": "Account Manager", "level": 4, "department": "Sales"},
            {"name": "Security Analyst", "level": 4, "department": "Infrastructure"},
        ],
        "customer_lifecycle": ["Lead", "RFP", "Proposal", "Negotiation", "Contract", "Onboarding", "Delivery", "Support", "Renewal"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "project_kickoff", "change_request", "incident_management",
                      "sla_breach", "resource_allocation", "timesheet_approval"],
        "dashboards": [
            {"title": "Delivery", "widgets": ["active_projects", "resource_utilization", "project_milestones", "timesheet_status"]},
            {"title": "Service Desk", "widgets": ["open_tickets", "sla_compliance", "resolution_time", "customer_satisfaction"]},
            {"title": "Sales", "widgets": ["pipeline_value", "win_rate", "contract_renewals"]},
        ],
        "forms": ["Project Request", "Change Request", "Incident Report", "Timesheet", "SLA Report", "Resource Request"],
        "automations": [
            {"trigger": "ticket_escalated", "actions": ["notify_senior_engineer", "update_sla_timer", "notify_customer", "escalate_to_manager"]},
            {"trigger": "project_milestone_completed", "actions": ["notify_stakeholders", "generate_report", "update_invoice_schedule", "schedule_review"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Delivery Head": ["delivery.*", "infrastructure.read", "resources.*"],
            "Project Manager": ["delivery.*", "resource.read", "timesheet.approve"],
            "Account Manager": ["sales.*", "customer.*", "project.read"],
        },
    },
    "digital_marketing": {
        "name": "Digital Marketing",
        "icon": "📱",
        "description": "Agency and in-house digital marketing management",
        "departments": [
            {"name": "Management", "teams": ["CEO", "Operations"]},
            {"name": "Strategy", "teams": ["Account Planning", "Client Servicing"]},
            {"name": "Creative", "teams": ["Design", "Copywriting", "Video"]},
            {"name": "Performance", "teams": ["SEM", "SEO", "Social Ads"]},
            {"name": "Content", "teams": ["Blog", "Social Media", "Email"]},
            {"name": "Analytics", "teams": ["Reporting", "Data Analysis"]},
            {"name": "Sales", "teams": ["New Business", "Account Management"]},
            {"name": "Finance", "teams": ["Accounts", "Media Buying"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Management"},
            {"name": "Account Director", "level": 2, "department": "Strategy"},
            {"name": "Account Manager", "level": 3, "department": "Strategy"},
            {"name": "Creative Director", "level": 3, "department": "Creative"},
            {"name": "Designer", "level": 4, "department": "Creative"},
            {"name": "SEO Specialist", "level": 4, "department": "Performance"},
            {"name": "SEM Specialist", "level": 4, "department": "Performance"},
            {"name": "Content Writer", "level": 4, "department": "Content"},
            {"name": "Social Media Manager", "level": 4, "department": "Content"},
            {"name": "Analytics Lead", "level": 4, "department": "Analytics"},
            {"name": "Media Buyer", "level": 4, "department": "Finance"},
        ],
        "customer_lifecycle": ["Lead", "Discovery Call", "Proposal", "Negotiation", "Onboarding", "Campaign", "Reporting", "Retainer"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "campaign_approval", "creative_review", "content_approval",
                      "media_buy_approval", "report_generation", "client_feedback"],
        "dashboards": [
            {"title": "Campaign Performance", "widgets": ["active_campaigns", "impressions", "clicks", "conversions", "spend"]},
            {"title": "Client Overview", "widgets": ["client_count", "retainer_value", "campaign_roi", "satisfaction_score"]},
            {"title": "Creative Pipeline", "widgets": ["pending_reviews", "content_calendar", "approval_status"]},
        ],
        "forms": ["Campaign Brief", "Creative Request", "Content Approval", "Media Plan", "Client Report", "Budget Proposal"],
        "automations": [
            {"trigger": "campaign_launched", "actions": ["notify_client", "tracking_setup", "schedule_report", "update_dashboard"]},
            {"trigger": "creative_approved", "actions": ["schedule_post", "notify_team", "update_calendar", "archive_assets"]},
            {"trigger": "report_ready", "actions": ["notify_client", "update_portal", "schedule_review_meeting"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Account Director": ["strategy.*", "creative.read", "performance.read", "finance.read"],
            "Account Manager": ["strategy.*", "client.*", "campaign.read"],
            "Creative Director": ["creative.*", "content.*"],
            "Designer": ["creative.write", "content.read"],
            "SEM Specialist": ["performance.sem.*", "analytics.read"],
            "Social Media Manager": ["content.social.*", "creative.read"],
        },
    },
    "finance": {
        "name": "Finance",
        "icon": "💰",
        "description": "Financial services, advisory, and wealth management",
        "departments": [
            {"name": "Executive", "teams": ["Board", "CEO Office"]},
            {"name": "Wealth Management", "teams": ["Advisory", "Portfolio Management"]},
            {"name": "Lending", "teams": ["Loan Processing", "Credit Assessment", "Collections"]},
            {"name": "Compliance", "teams": ["Regulatory", "KYC/AML", "Audit"]},
            {"name": "Operations", "teams": ["Back Office", "Settlements"]},
            {"name": "Sales", "teams": ["Relationship Managers", "Business Development"]},
            {"name": "Finance & Accounting", "teams": ["Accounts", "Treasury"]},
            {"name": "Risk Management", "teams": ["Credit Risk", "Market Risk", "Operational Risk"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Executive"},
            {"name": "Chief Risk Officer", "level": 2, "department": "Risk Management"},
            {"name": "Head of Wealth", "level": 2, "department": "Wealth Management"},
            {"name": "Relationship Manager", "level": 4, "department": "Sales"},
            {"name": "Financial Advisor", "level": 4, "department": "Wealth Management"},
            {"name": "Credit Analyst", "level": 4, "department": "Risk Management"},
            {"name": "Compliance Officer", "level": 4, "department": "Compliance"},
            {"name": "Loan Officer", "level": 5, "department": "Lending"},
            {"name": "Operations Executive", "level": 5, "department": "Operations"},
        ],
        "customer_lifecycle": ["Lead", "Needs Assessment", "Proposal", "KYC", "Onboarding", "Active", "Review", "Renewal/Closure"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "kyc_verification", "loan_application", "credit_assessment",
                      "compliance_check", "portfolio_review", "transaction_approval"],
        "dashboards": [
            {"title": "Portfolio Overview", "widgets": ["aum", "active_clients", "portfolio_performance", "revenue"]},
            {"title": "Lending", "widgets": ["loan_applications", "disbursements", "collections", "npa_status"]},
            {"title": "Compliance", "widgets": ["pending_kyc", "audit_status", "regulatory_filings"]},
        ],
        "forms": ["KYC Form", "Loan Application", "Investment Proposal", "Risk Assessment", "Compliance Report"],
        "automations": [
            {"trigger": "kyc_completed", "actions": ["approve_customer", "create_portfolio", "notify_rm", "send_welcome_kit"]},
            {"trigger": "loan_approved", "actions": ["generate_agreement", "schedule_disbursement", "notify_customer", "update_crm"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Chief Risk Officer": ["risk.*", "compliance.*", "lending.read"],
            "Head of Wealth": ["wealth.*", "sales.read", "portfolio.*"],
            "Relationship Manager": ["sales.*", "customer.*", "portfolio.read"],
            "Compliance Officer": ["compliance.*", "kyc.*", "customer.read"],
            "Credit Analyst": ["risk.credit.*", "lending.read"],
        },
    },
    "insurance": {
        "name": "Insurance",
        "icon": "🛡️",
        "description": "Insurance broking, underwriting, and claims management",
        "departments": [
            {"name": "Management", "teams": ["CEO", "Operations"]},
            {"name": "Sales", "teams": ["Agents", "Brokers", "Corporate Sales"]},
            {"name": "Underwriting", "teams": ["Life", "Health", "General"]},
            {"name": "Claims", "teams": ["Processing", "Investigation", "Settlement"]},
            {"name": "Compliance", "teams": ["Regulatory", "Training"]},
            {"name": "Finance", "teams": ["Accounts", "Premiums"]},
            {"name": "Customer Service", "teams": ["Support", "Policy Services"]},
        ],
        "roles": [
            {"name": "CEO", "level": 1, "department": "Management"},
            {"name": "Chief Underwriter", "level": 2, "department": "Underwriting"},
            {"name": "Sales Manager", "level": 3, "department": "Sales"},
            {"name": "Insurance Agent", "level": 4, "department": "Sales"},
            {"name": "Underwriter", "level": 4, "department": "Underwriting"},
            {"name": "Claims Manager", "level": 3, "department": "Claims"},
            {"name": "Claims Officer", "level": 5, "department": "Claims"},
            {"name": "Compliance Officer", "level": 4, "department": "Compliance"},
            {"name": "Customer Service Rep", "level": 5, "department": "Customer Service"},
        ],
        "customer_lifecycle": ["Lead", "Needs Analysis", "Proposal", "Underwriting", "Issuance", "Active", "Claim", "Renewal"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "policy_issuance", "claim_filing", "claim_assessment",
                      "underwriting_review", "renewal_processing", "agent_commission"],
        "dashboards": [
            {"title": "Sales Overview", "widgets": ["policies_issued", "premium_collected", "agent_performance", "conversion_rate"]},
            {"title": "Claims", "widgets": ["claims_filed", "pending_assessment", "settlement_rate", "claim_amount"]},
            {"title": "Underwriting", "widgets": ["proposals_pending", "risk_assessment", "policy_portfolio"]},
        ],
        "forms": ["Policy Application", "Claim Form", "Underwriting Assessment", "Renewal Notice", "Commission Statement"],
        "automations": [
            {"trigger": "policy_issued", "actions": ["generate_policy_document", "notify_customer", "update_agent_portal", "schedule_renewal_reminder"]},
            {"trigger": "claim_filed", "actions": ["assign_claims_officer", "notify_customer", "initiate_assessment", "update_status"]},
            {"trigger": "claim_approved", "actions": ["process_payment", "notify_customer", "close_claim", "update_policy"]},
        ],
        "permissions": {
            "CEO": ["all"],
            "Sales Manager": ["sales.*", "agent.*", "customer.read"],
            "Chief Underwriter": ["underwriting.*", "risk.*", "policy.read"],
            "Claims Manager": ["claims.*", "settlement.approve", "policy.read"],
            "Insurance Agent": ["sales.write", "customer.read", "policy.read"],
            "Underwriter": ["underwriting.write", "risk.assess", "policy.read"],
        },
    },
    "law_firm": {
        "name": "Law Firm",
        "icon": "⚖️",
        "description": "Legal practice management with case and client management",
        "departments": [
            {"name": "Partnership", "teams": ["Senior Partners", "Junior Partners"]},
            {"name": "Practice Areas", "teams": ["Corporate", "Litigation", "Family", "Criminal", "Intellectual Property", "Real Estate"]},
            {"name": "Paralegal", "teams": ["Research", "Drafting", "Compliance"]},
            {"name": "Client Services", "teams": ["Intake", "Support"]},
            {"name": "Finance", "teams": ["Billing", "Accounts", "Trust Accounting"]},
            {"name": "Administration", "teams": ["Office Management", "HR"]},
        ],
        "roles": [
            {"name": "Senior Partner", "level": 1, "department": "Partnership"},
            {"name": "Junior Partner", "level": 2, "department": "Partnership"},
            {"name": "Practice Head", "level": 3, "department": "Practice Areas"},
            {"name": "Senior Associate", "level": 4, "department": "Practice Areas"},
            {"name": "Associate", "level": 5, "department": "Practice Areas"},
            {"name": "Paralegal", "level": 5, "department": "Paralegal"},
            {"name": "Legal Secretary", "level": 6, "department": "Administration"},
            {"name": "Billing Specialist", "level": 5, "department": "Finance"},
        ],
        "customer_lifecycle": ["Lead", "Consultation", "Engagement", "Case Strategy", "Active Case", "Hearing", "Resolution", "Billing", "Closed"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "case_intake", "document_drafting", "court_filing",
                      "billing_time_entry", "conflict_check", "settlement_approval"],
        "dashboards": [
            {"title": "Practice Overview", "widgets": ["active_cases", "pending_filings", "upcoming_hearings", "billable_hours"]},
            {"title": "Financial", "widgets": ["collections", "outstanding_fees", "trust_accounts", "realization_rate"]},
        ],
        "forms": ["Case Intake", "Conflict Check", "Court Filing", "Time Entry", "Expense Entry", "Settlement Agreement"],
        "automations": [
            {"trigger": "case_opened", "actions": ["assign_attorney", "create_case_file", "conflict_check", "send_engagement_letter", "setup_billing"]},
            {"trigger": "hearing_scheduled", "actions": ["notify_attorney", "prepare_case_brief", "update_calendar", "send_reminder"]},
            {"trigger": "settlement_approved", "actions": ["draft_settlement_agreement", "notify_client", "schedule_signing", "generate_invoice"]},
        ],
        "permissions": {
            "Senior Partner": ["all"],
            "Junior Partner": ["practice.*", "finance.read", "client.*"],
            "Practice Head": ["practice.*", "associate.*", "client.read"],
            "Senior Associate": ["practice.write", "case.*", "time_entry"],
            "Associate": ["practice.write", "case.read", "time_entry"],
            "Paralegal": ["paralegal.*", "case.read", "drafting"],
        },
    },
    "hotel": {
        "name": "Hotel",
        "icon": "🏨",
        "description": "Full-service hotel with reservations, housekeeping, and F&B",
        "departments": [
            {"name": "Management", "teams": ["GM Office", "Executive Committee"]},
            {"name": "Front Office", "teams": ["Reception", "Concierge", "Reservations"]},
            {"name": "Housekeeping", "teams": ["Room Cleaning", "Laundry", "Public Areas"]},
            {"name": "F&B", "teams": ["Kitchen", "Restaurant", "Room Service", "Bar"]},
            {"name": "Sales & Marketing", "teams": ["Events", "Corporate Sales", "Digital"]},
            {"name": "Finance", "teams": ["Accounts", "Audit", "Payroll"]},
            {"name": "Engineering", "teams": ["Maintenance", "Security"]},
            {"name": "HR", "teams": ["Staff Management", "Training"]},
        ],
        "roles": [
            {"name": "General Manager", "level": 1, "department": "Management"},
            {"name": "Front Office Manager", "level": 2, "department": "Front Office"},
            {"name": "Housekeeping Manager", "level": 2, "department": "Housekeeping"},
            {"name": "F&B Manager", "level": 2, "department": "F&B"},
            {"name": "Chef", "level": 3, "department": "F&B"},
            {"name": "Receptionist", "level": 4, "department": "Front Office"},
            {"name": "Room Attendant", "level": 5, "department": "Housekeeping"},
            {"name": "Sales Manager", "level": 3, "department": "Sales & Marketing"},
            {"name": "Accountant", "level": 4, "department": "Finance"},
            {"name": "Concierge", "level": 4, "department": "Front Office"},
        ],
        "customer_lifecycle": ["Inquiry", "Booking", "Check-in", "Stay", "Check-out", "Feedback", "Repeat Guest"],
        "workflows": ["booking_reservation", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "guest_checkin", "guest_checkout", "room_maintenance",
                      "event_booking", "complaint_handling", "group_booking"],
        "dashboards": [
            {"title": "Front Office", "widgets": ["occupancy_rate", "arrivals_today", "departures_today", "revenue_per_room"]},
            {"title": "Operations", "widgets": ["rooms_cleaned", "maintenance_requests", "f&b_revenue", "events_today"]},
            {"title": "Finance", "widgets": ["daily_revenue", "accounts_receivable", "average_daily_rate"]},
        ],
        "forms": ["Booking", "Check-in Form", "Room Service Order", "Maintenance Request", "Event Booking", "Feedback Form"],
        "automations": [
            {"trigger": "booking_confirmed", "actions": ["assign_room", "send_confirmation", "notify_housekeeping", "update_availability"]},
            {"trigger": "guest_checkin", "actions": ["activate_room_keys", "notify_concierge", "update_room_status", "send_welcome"]},
            {"trigger": "guest_checkout", "actions": ["generate_invoice", "process_payment", "update_room_status", "send_feedback_link", "update_loyalty"]},
        ],
        "permissions": {
            "General Manager": ["all"],
            "Front Office Manager": ["front_office.*", "reservations.*", "guest.read"],
            "Housekeeping Manager": ["housekeeping.*", "maintenance.request"],
            "F&B Manager": ["fandb.*", "inventory.read"],
            "Sales Manager": ["sales.*", "events.*", "guest.read"],
        },
    },
    "restaurant": {
        "name": "Restaurant",
        "icon": "🍽️",
        "description": "Restaurant with POS, reservations, and kitchen management",
        "departments": [
            {"name": "Management", "teams": ["Owner", "Manager"]},
            {"name": "Kitchen", "teams": ["Chefs", "Prep", "Dishwashing"]},
            {"name": "Service", "teams": ["Wait Staff", "Host", "Bartenders"]},
            {"name": "Finance", "teams": ["Billing", "Accounts"]},
            {"name": "Marketing", "teams": ["Social Media", "Events"]},
        ],
        "roles": [
            {"name": "Owner/GM", "level": 1, "department": "Management"},
            {"name": "Restaurant Manager", "level": 2, "department": "Management"},
            {"name": "Head Chef", "level": 2, "department": "Kitchen"},
            {"name": "Sous Chef", "level": 3, "department": "Kitchen"},
            {"name": "Line Cook", "level": 4, "department": "Kitchen"},
            {"name": "Head Server", "level": 3, "department": "Service"},
            {"name": "Server", "level": 4, "department": "Service"},
            {"name": "Bartender", "level": 4, "department": "Service"},
            {"name": "Host", "level": 5, "department": "Service"},
        ],
        "customer_lifecycle": ["Reservation", "Walk-in", "Seated", "Order", "Dining", "Payment", "Feedback"],
        "workflows": ["booking_reservation", "leave_approval", "expense_approval", "support_ticket",
                      "reservation_management", "inventory_order", "menu_change_approval",
                      "health_inspection", "event_booking"],
        "dashboards": [
            {"title": "Restaurant Overview", "widgets": ["reservations_today", "covers", "average_check", "table_turnover"]},
            {"title": "Kitchen", "widgets": ["prep_status", "food_cost", "waste_tracking", "popular_items"]},
            {"title": "Sales", "widgets": ["daily_sales", "payment_methods", "peak_hours"]},
        ],
        "forms": ["Reservation", "Menu Change Request", "Inventory Order", "Health Inspection", "Event Booking"],
        "automations": [
            {"trigger": "reservation_made", "actions": ["assign_table", "send_confirmation", "update_booking_system", "send_reminder"]},
            {"trigger": "order_completed", "actions": ["process_payment", "update_inventory", "update_sales_report"]},
        ],
        "permissions": {
            "Owner/GM": ["all"],
            "Restaurant Manager": ["operations.*", "staff.*", "finance.read"],
            "Head Chef": ["kitchen.*", "inventory.*", "menu.*"],
            "Manager": ["service.*", "reservations.*", "customer.read"],
        },
    },
    "ngo": {
        "name": "NGO",
        "icon": "🤝",
        "description": "Non-profit with donor management and program tracking",
        "departments": [
            {"name": "Board", "teams": ["Trustees", "Advisory"]},
            {"name": "Executive", "teams": ["CEO", "Operations"]},
            {"name": "Programs", "teams": ["Project Implementation", "Field Staff", "Monitoring"]},
            {"name": "Fundraising", "teams": ["Donor Relations", "Grants", "Events"]},
            {"name": "Finance", "teams": ["Accounts", "Audit", "Compliance"]},
            {"name": "Communications", "teams": ["PR", "Social Media", "Publications"]},
            {"name": "HR & Admin", "teams": ["Volunteers", "Staff", "Administration"]},
        ],
        "roles": [
            {"name": "Executive Director", "level": 1, "department": "Executive"},
            {"name": "Program Director", "level": 2, "department": "Programs"},
            {"name": "Program Manager", "level": 3, "department": "Programs"},
            {"name": "Field Officer", "level": 4, "department": "Programs"},
            {"name": "Fundraising Manager", "level": 3, "department": "Fundraising"},
            {"name": "Donor Relations Officer", "level": 4, "department": "Fundraising"},
            {"name": "Finance Manager", "level": 3, "department": "Finance"},
            {"name": "Communications Officer", "level": 4, "department": "Communications"},
            {"name": "Volunteer Coordinator", "level": 4, "department": "HR & Admin"},
        ],
        "customer_lifecycle": ["Awareness", "Engagement", "Donation", "Stewardship", "Retention", "Advocacy"],
        "workflows": ["donor_management", "leave_approval", "expense_approval", "grant_application",
                      "volunteer_registration", "event_management", "project_reporting",
                      "beneficiary_registration", "donation_receipt"],
        "dashboards": [
            {"title": "Program Impact", "widgets": ["active_projects", "beneficiaries_served", "program_budget", "field_reports"]},
            {"title": "Fundraising", "widgets": ["donations_this_month", "donor_count", "grant_status", "fundraising_goal"]},
            {"title": "Volunteers", "widgets": ["active_volunteers", "hours_contributed", "upcoming_events"]},
        ],
        "forms": ["Donor Registration", "Grant Application", "Volunteer Registration", "Beneficiary Form", "Project Report", "Expense Report"],
        "automations": [
            {"trigger": "donation_received", "actions": ["generate_receipt", "send_thank_you", "update_donor_record", "update_dashboard"]},
            {"trigger": "grant_approved", "actions": ["allocate_budget", "assign_project_team", "notify_stakeholders", "schedule_reporting"]},
            {"trigger": "volunteer_registered", "actions": ["send_welcome", "assign_orientation", "add_to_roster", "notify_coordinator"]},
        ],
        "permissions": {
            "Executive Director": ["all"],
            "Program Director": ["programs.*", "finance.read", "field.*"],
            "Program Manager": ["programs.*", "beneficiary.*", "field.read"],
            "Fundraising Manager": ["fundraising.*", "donor.*", "finance.read"],
            "Finance Manager": ["finance.*", "compliance.*", "grant.read"],
        },
    },
    "government": {
        "name": "Government",
        "icon": "🏛️",
        "description": "Government department with citizen services and compliance",
        "departments": [
            {"name": "Administration", "teams": ["Commissioner Office", "Secretariat"]},
            {"name": "Citizen Services", "teams": ["Front Desk", "Grievances", "Information"]},
            {"name": "Finance", "teams": ["Budget", "Accounts", "Audit"]},
            {"name": "HR", "teams": ["Staff Management", "Payroll", "Pensions"]},
            {"name": "Legal", "teams": ["Compliance", "Prosecution"]},
            {"name": "IT", "teams": ["Systems", "E-Governance"]},
        ],
        "roles": [
            {"name": "Commissioner/Secretary", "level": 1, "department": "Administration"},
            {"name": "Joint Commissioner", "level": 2, "department": "Administration"},
            {"name": "Deputy Commissioner", "level": 3, "department": "Administration"},
            {"name": "Department Head", "level": 3, "department": "Administration"},
            {"name": "Section Officer", "level": 4, "department": "Citizen Services"},
            {"name": "Assistant", "level": 5, "department": "Citizen Services"},
            {"name": "Finance Officer", "level": 4, "department": "Finance"},
            {"name": "Legal Advisor", "level": 4, "department": "Legal"},
            {"name": "IT Officer", "level": 4, "department": "IT"},
        ],
        "customer_lifecycle": ["Inquiry", "Application", "Verification", "Processing", "Approval", "Issuance", "Feedback"],
        "workflows": ["citizen_service_request", "leave_approval", "expense_approval", "file_tracking",
                      "grievance_redressal", "procurement_approval", "budget_approval",
                      "document_approval", "committee_meeting"],
        "dashboards": [
            {"title": "Citizen Services", "widgets": ["pending_applications", "grievances", "service_metrics", "resolution_time"]},
            {"title": "Administration", "widgets": ["file_status", "meetings", "notifications", "staff_attendance"]},
            {"title": "Budget", "widgets": ["budget_utilization", "expenditure", "savings"]},
        ],
        "forms": ["Service Application", "Grievance Form", "File Note", "Procurement Request", "Meeting Minutes"],
        "automations": [
            {"trigger": "application_submitted", "actions": ["assign_officer", "send_acknowledgment", "start_tat_timer", "notify_applicant"]},
            {"trigger": "application_approved", "actions": ["generate_certificate", "notify_applicant", "update_records", "close_file"]},
        ],
        "permissions": {
            "Commissioner/Secretary": ["all"],
            "Joint Commissioner": ["administration.*", "departments.*", "finance.read"],
            "Department Head": ["department.*", "staff.*", "citizen_services.*"],
            "Section Officer": ["citizen_services.*", "file.*", "grievance.*"],
        },
    },
    "startup": {
        "name": "Startup",
        "icon": "🚀",
        "description": "Fast-growing startup with lean team and agile workflows",
        "departments": [
            {"name": "Founders", "teams": ["CEO", "CTO", "COO"]},
            {"name": "Engineering", "teams": ["Product Dev", "Infrastructure"]},
            {"name": "Product", "teams": ["Product Management", "Design"]},
            {"name": "Growth", "teams": ["Marketing", "Sales", "Partnerships"]},
            {"name": "Operations", "teams": ["Finance", "HR", "Legal"]},
        ],
        "roles": [
            {"name": "CEO/Founder", "level": 1, "department": "Founders"},
            {"name": "CTO/Co-Founder", "level": 1, "department": "Founders"},
            {"name": "Product Lead", "level": 2, "department": "Product"},
            {"name": "Engineering Lead", "level": 2, "department": "Engineering"},
            {"name": "Full Stack Developer", "level": 3, "department": "Engineering"},
            {"name": "Designer", "level": 3, "department": "Product"},
            {"name": "Growth Lead", "level": 2, "department": "Growth"},
            {"name": "Operations Manager", "level": 3, "department": "Operations"},
        ],
        "customer_lifecycle": ["Lead", "Demo", "Trial", "Onboarding", "Active", "Expansion", "Advocacy"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "bug_reporting",
                      "feature_request", "deployment_approval", "investor_reporting",
                      "hiring_approval", "tool_procurement"],
        "dashboards": [
            {"title": "Growth Metrics", "widgets": ["mrr", "active_users", "churn_rate", "growth_rate"]},
            {"title": "Development", "widgets": ["sprint_progress", "deployments", "issues", "velocity"]},
            {"title": "Fundraising", "widgets": ["burn_rate", "runway", "investor_pipeline"]},
        ],
        "forms": ["Feature Request", "Bug Report", "Hiring Request", "Tool Procurement", "Investor Update"],
        "automations": [
            {"trigger": "user_signed_up", "actions": ["send_welcome", "assign_onboarding", "create_workspace", "schedule_demo"]},
            {"trigger": "trial_expiring", "actions": ["notify_sales", "send_offer", "schedule_followup"]},
        ],
        "permissions": {
            "CEO/Founder": ["all"],
            "CTO/Co-Founder": ["engineering.*", "product.*", "infrastructure.*"],
            "Product Lead": ["product.*", "design.*", "engineering.read"],
            "Engineering Lead": ["engineering.*", "devops.*", "qa.*"],
            "Growth Lead": ["growth.*", "marketing.*", "sales.*", "customer.read"],
        },
    },
    "consultancy": {
        "name": "Consultancy",
        "icon": "📊",
        "description": "Management and strategy consulting with project-based delivery",
        "departments": [
            {"name": "Partnership", "teams": ["Managing Partner", "Partners"]},
            {"name": "Practice Areas", "teams": ["Strategy", "Operations", "Technology", "Human Capital"]},
            {"name": "Delivery", "teams": ["Project Management", "Consultants", "Analysts"]},
            {"name": "Sales", "teams": ["Business Development", "Account Management"]},
            {"name": "Marketing", "teams": ["Thought Leadership", "Events"]},
            {"name": "Finance", "teams": ["Accounts", "Billing"]},
            {"name": "HR", "teams": ["Talent", "L&D"]},
        ],
        "roles": [
            {"name": "Managing Partner", "level": 1, "department": "Partnership"},
            {"name": "Partner", "level": 2, "department": "Partnership"},
            {"name": "Practice Lead", "level": 3, "department": "Practice Areas"},
            {"name": "Principal Consultant", "level": 4, "department": "Delivery"},
            {"name": "Senior Consultant", "level": 5, "department": "Delivery"},
            {"name": "Consultant", "level": 6, "department": "Delivery"},
            {"name": "Analyst", "level": 7, "department": "Delivery"},
            {"name": "Business Development Manager", "level": 4, "department": "Sales"},
        ],
        "customer_lifecycle": ["Lead", "Discovery", "Proposal", "Engagement", "Execution", "Deliverable", "Review", "Extension"],
        "workflows": ["customer_management", "leave_approval", "expense_approval", "invoice_approval",
                      "support_ticket", "engagement_kickoff", "deliverable_review", "timesheet_approval",
                      "resource_allocation", "travel_approval", "statement_of_work"],
        "dashboards": [
            {"title": "Engagements", "widgets": ["active_projects", "utilization_rate", "billable_hours", "revenue_forecast"]},
            {"title": "Pipeline", "widgets": ["proposals_pending", "win_rate", "pipeline_value", "engagement_duration"]},
            {"title": "People", "widgets": ["consultant_utilization", "open_roles", "skill_coverage", "satisfaction"]},
        ],
        "forms": ["Engagement Proposal", "Statement of Work", "Timesheet", "Expense Report", "Deliverable Review", "Travel Request"],
        "automations": [
            {"trigger": "engagement_signed", "actions": ["assemble_team", "schedule_kickoff", "create_project", "send_welcome_pack", "setup_billing"]},
            {"trigger": "deliverable_submitted", "actions": ["assign_reviewer", "notify_client", "schedule_presentation", "update_project_status"]},
            {"trigger": "timesheet_submitted", "actions": ["approve_timesheet", "update_utilization", "trigger_billing", "notify_manager"]},
        ],
        "permissions": {
            "Managing Partner": ["all"],
            "Partner": ["practice.*", "delivery.*", "finance.read", "sales.*"],
            "Practice Lead": ["practice.*", "delivery.*", "resource.*"],
            "Principal Consultant": ["delivery.*", "timesheet.*", "client.read"],
            "Senior Consultant": ["delivery.write", "timesheet.write", "client.read"],
            "Analyst": ["delivery.read", "research.*", "timesheet.write"],
        },
    },
    "custom_business": {
        "name": "Custom Business",
        "icon": "🔧",
        "description": "Tailor-made configuration for any business type",
        "departments": [
            {"name": "Executive", "teams": ["Leadership", "Strategy"]},
            {"name": "Operations", "teams": ["Day-to-Day", "Logistics"]},
            {"name": "Sales & Marketing", "teams": ["Sales", "Marketing", "Customer Relations"]},
            {"name": "Finance", "teams": ["Accounting", "Payroll"]},
            {"name": "HR & Admin", "teams": ["People", "Administration"]},
            {"name": "Customer Support", "teams": ["Service", "Success"]},
        ],
        "roles": [
            {"name": "CEO/Director", "level": 1, "department": "Executive"},
            {"name": "Operations Head", "level": 2, "department": "Operations"},
            {"name": "Department Manager", "level": 3, "department": "Operations"},
            {"name": "Team Lead", "level": 4, "department": "Operations"},
            {"name": "Sales Manager", "level": 3, "department": "Sales & Marketing"},
            {"name": "Finance Manager", "level": 3, "department": "Finance"},
            {"name": "HR Manager", "level": 3, "department": "HR & Admin"},
            {"name": "Executive", "level": 5, "department": "Operations"},
        ],
        "customer_lifecycle": ["Lead", "Inquiry", "Quote", "Negotiation", "Sale", "Delivery", "Support", "Follow-up"],
        "workflows": ["customer_management", "leave_approval", "purchase_request", "expense_approval",
                      "invoice_approval", "support_ticket"],
        "dashboards": [
            {"title": "Business Overview", "widgets": ["active_leads", "pending_quotes", "open_tasks", "revenue"]},
            {"title": "Operations", "widgets": ["team_status", "pending_approvals", "recent_activities"]},
        ],
        "forms": ["Lead Capture", "Quote", "Invoice", "Task", "Expense", "Leave Request"],
        "automations": [
            {"trigger": "lead_created", "actions": ["assign_owner", "send_welcome", "create_task"]},
            {"trigger": "invoice_paid", "actions": ["update_accounts", "notify_finance", "send_receipt"]},
        ],
        "permissions": {
            "CEO/Director": ["all"],
            "Operations Head": ["operations.*", "sales.read", "finance.read"],
            "Department Manager": ["operations.*", "staff.read"],
            "Team Lead": ["operations.write", "task.assign"],
        },
    },
}

BUSINESS_ICONS = {
    "manufacturing": "🏭", "construction": "🏗️", "healthcare": "🏥", "hospital": "🏨",
    "clinic": "🩺", "pharmacy": "💊", "school": "🏫", "college": "🎓", "university": "🏛️",
    "retail_store": "🏪", "wholesale": "📦", "logistics": "🚚", "transportation": "🚌",
    "real_estate": "🏠", "software_company": "💻", "it_services": "🖥️", "digital_marketing": "📱",
    "finance": "💰", "insurance": "🛡️", "law_firm": "⚖️", "hotel": "🏨",
    "restaurant": "🍽️", "ngo": "🤝", "government": "🏛️", "startup": "🚀",
    "consultancy": "📊", "custom_business": "🔧",
}

WORKFLOW_DEFINITIONS = {
    "customer_management": {
        "name": "Customer Management",
        "description": "End-to-end customer lifecycle management",
        "category": "crm",
        "entity_type": "customer",
    },
    "leave_approval": {
        "name": "Leave Approval",
        "description": "Employee leave request and approval process",
        "category": "hr",
        "entity_type": "user",
    },
    "purchase_request": {
        "name": "Purchase Request",
        "description": "Internal purchase request and procurement process",
        "category": "procurement",
        "entity_type": "task",
    },
    "expense_approval": {
        "name": "Expense Approval",
        "description": "Employee expense reimbursement approval",
        "category": "finance",
        "entity_type": "task",
    },
    "invoice_approval": {
        "name": "Invoice Approval",
        "description": "Invoice generation and approval workflow",
        "category": "finance",
        "entity_type": "invoice",
    },
    "support_ticket": {
        "name": "Support Ticket",
        "description": "Customer support ticket management and escalation",
        "category": "support",
        "entity_type": "ticket",
    },
    "bug_reporting": {
        "name": "Bug Reporting",
        "description": "Software bug tracking and resolution",
        "category": "development",
        "entity_type": "task",
    },
    "feature_request": {
        "name": "Feature Request",
        "description": "Product feature request management",
        "category": "development",
        "entity_type": "task",
    },
    "deployment_approval": {
        "name": "Deployment Approval",
        "description": "Code deployment approval and release process",
        "category": "development",
        "entity_type": "task",
    },
    "site_inspection": {
        "name": "Site Inspection",
        "description": "Construction site inspection and quality check",
        "category": "operations",
        "entity_type": "task",
    },
    "material_request": {
        "name": "Material Request",
        "description": "Material requisition and approval for projects",
        "category": "procurement",
        "entity_type": "task",
    },
    "patient_registration": {
        "name": "Patient Registration",
        "description": "New patient intake and registration workflow",
        "category": "healthcare",
        "entity_type": "customer",
    },
    "appointment_booking": {
        "name": "Appointment Booking",
        "description": "Patient appointment scheduling and confirmation",
        "category": "healthcare",
        "entity_type": "lead",
    },
    "discharge_process": {
        "name": "Discharge Process",
        "description": "Patient discharge planning and execution",
        "category": "healthcare",
        "entity_type": "task",
    },
    "student_admission": {
        "name": "Student Admission",
        "description": "Student enrollment and admission process",
        "category": "education",
        "entity_type": "lead",
    },
    "booking_reservation": {
        "name": "Booking / Reservation",
        "description": "Customer booking and reservation management",
        "category": "hospitality",
        "entity_type": "lead",
    },
    "donor_management": {
        "name": "Donor Management",
        "description": "Donor engagement and donation tracking",
        "category": "nonprofit",
        "entity_type": "customer",
    },
    "claim_filing": {
        "name": "Claim Filing",
        "description": "Insurance claim submission and processing",
        "category": "insurance",
        "entity_type": "task",
    },
    "case_intake": {
        "name": "Case Intake",
        "description": "Legal case intake and conflict check",
        "category": "legal",
        "entity_type": "lead",
    },
}


def get_all_templates():
    result = {}
    for key, tmpl in BUSINESS_TEMPLATES.items():
        result[key] = {
            "id": key,
            "name": tmpl["name"],
            "icon": tmpl.get("icon", "🔧"),
            "description": tmpl["description"],
        }
    return result


def get_template(business_type):
    return BUSINESS_TEMPLATES.get(business_type)


def get_departments(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["departments"]
    return tmpl["departments"]


def get_roles(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["roles"]
    return tmpl["roles"]


def get_customer_lifecycle(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["customer_lifecycle"]
    return tmpl["customer_lifecycle"]


def get_workflows(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["workflows"]
    return tmpl["workflows"]


def get_dashboards(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["dashboards"]
    return tmpl["dashboards"]


def get_forms(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["forms"]
    return tmpl["forms"]


def get_automations(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["automations"]
    return tmpl["automations"]


def get_permissions(business_type):
    tmpl = BUSINESS_TEMPLATES.get(business_type)
    if not tmpl:
        return BUSINESS_TEMPLATES["custom_business"]["permissions"]
    return tmpl["permissions"]


def get_workflow_definition(workflow_key):
    return WORKFLOW_DEFINITIONS.get(workflow_key)
